name: ma
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cudatoolkit-dev=11.7.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.2.1
  - pip=24.0
  - python=3.8.18
  - readline=8.2
  - setuptools=69.1.0
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
    - absl-py==2.1.0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - cachetools==5.3.2
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - docker-pycreds==0.4.0
    - drjit==0.2.2
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.42
    - google-auth==2.28.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.60.1
    - idna==3.6
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==7.0.1
    - lightning-utilities==0.10.1
    - lpips==0.1.4
    - markdown==3.5.2
    - markupsafe==2.1.5
    - mitsuba==3.0.2
    - multidict==6.0.5
    - numpy==1.24.4
    - oauthlib==3.2.2
    - packaging==23.2
    - pathtools==0.1.2
    - pillow==10.2.0
    - promise==2.3
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pydeprecate==0.3.2
    - pytorch-lightning==1.7.7
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.10.1
    - sentry-sdk==1.40.4
    - setproctitle==1.3.3
    - shortuuid==1.0.11
    - six==1.16.0
    - smmap==5.0.1
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tinycudann==1.7
    - torch==1.13.0+cu117
    - torchaudio==0.13.0+cu117
    - torchmetrics==0.11.2
    - torchvision==0.14.0+cu117
    - tqdm==4.66.2
    - typing-extensions==4.9.0
    - urllib3==2.2.1
    - wandb==0.13.5
    - werkzeug==3.0.1
    - yarl==1.9.4
    - zipp==3.17.0
